# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4TrcgoJM009aVih16HHzA0KZbl7Ks14
"""

class Student():
  def __init__(self, name, age, matric):
    self.name = name
    self.age = age
    self.matric = matric

  def display(self):
    print("Name:", self.name)
    print("Age:", self.age)
    print("Matric No.:", self.matric)

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}, Matric no.: {self.matric}"

p1 = Student("Martha", 36, "1310897")
p2 = Student("Daisy", 24, "1910262")

print(p1)
print(p2)

class Person():
  def __init__(self, name, age, matric):
    self.name = name
    self.age = age
    self.matric = matric
  def display(self):
    print("Name:", self.name)
    print("Age:", self.age)
    print("Matric no.:", self.matric)

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}, Matric.no.: {self.matric}"

class Student(Person):
  pass

x = Student("Angela", "23", "1910262")
x.display()

