# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gEvo-ch5T08IDLA-4IPBMAg4SMBcYlvc
"""

#function largest number between two numbers
def large (x,y):
  if x > y:
    return x
  else:
    return y
    
print("Largest of 30,50 is :", large (30,50))
print("Largest of 20,30 is :", large(20,30))

#function largest number between three numbers
def large (x,y,z):
  if x > y and x > z:
    return x
  elif y > x and y > z:
    return y
  else:
    return z

print("Largest of 30,50,70 is :", large (30,50,70))
print("Largest of 20,30,60 is :", large(20,30,60))

